### ISSUE TITLE
视频页无法替换播放列表

### ISSUE THREAD

**Issue by rockbenben** [JohnCido/BilibiliPlaylist#16]
点击播放列表后，播放一个视频后停止。

试过新版和旧版界面，播放列表都未被替换。

**Comment by JohnCido** [comment]
@rockbenben  因为B站的前端代码有可能随时更改，并且新版本播放器依然没有正式上线，所以在那之前暂时不会推出插件的新版本，目前仅针对收藏夹获取以及弹出窗口进行代码重写，具体可查看 [v2分支](https://github.com/JohnCido/BilibiliPlaylist/tree/v2) 。

**Comment by JohnCido** [comment]
2.0.1版本更新已上线，列表替换问题通过完全自定义的浮层列表解决，欢迎尝试新版本并提出使用建议。
